DNZ144/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='django_auth'),
    path('groups/', include('group.urls'), name='group'),
    path('registration/', include('accounts.urls'), name='registration'),
    path('accounting/', include('accounting.urls'), name='accounting'),
    path('', views.home_view, name='home'),
    path('contacts/', views.contacts_view, name='contacts'),
    path('info/', views.info_view, name='info'),
    path('info/staff', views.staff_view, name='staff'),
    path('info/schedule', views.schedule_view, name='schedule'),
    path('services/', include('services.urls'), name='services'),
    path('error_500', views.error_500_view, name='error_500'),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
	path('', views.SignUp.as_view(), name='signup'),
	path('details/<pk>', views.AccountDetailView.as_view(), name='account_detail'),
	path('logout', views.logout_view, name='logout'),
	path('login', views.UserLoginView.as_view(), name='login'),
	path('profile/update/<pk>', views.ProfileUpdateView.as_view(), name='profile_update'),
	path('password_reset', views.UserPasswordResetView.as_view(), name='reset_pass'),
	path('password_reset_confirm/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='reset'),
	path('password/reset/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

group/urls.py
from django.urls import path, include
from . import views

app_name = 'group'

urlpatterns = [
	
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class ApiUser(AbstractUser):
    phone = models.CharField(max_length=10, blank=True, null=True,
                             unique=True)
    birth_date = models.DateField(null=True, blank=True)

    class Meta(AbstractUser.Meta):
        db_table = 'accounts_user'

    def __str__(self):
        return "@{}".format(self.username)

    def get_absolute_url(self):
        return reverse('accounts:account_detail', args=[str(self.id)])

    def get_group_list(self):
        group_list = []
        for kid in self.kids.all():
            group_list.append(kid.groups.first())
        return group_list

    def has_group(self):
        if len(self.get_group_list()) > 0:
            return True
        return False

    def get_balanse(self):
        from accounting.models import Kassa
        balance = 0
        if len(self.get_group_list()) > 0:
            for kassa in Kassa.objects.filter(group=self.get_group_list()[0]):
                # TODO: KID FIRST???
                if kassa.kid_balance(self.kids.first()):
                    balance += kassa.kid_balance(self.kids.first())['balance']
            return balance

accounts/forms.py
# from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from accounts.models import ApiUser
from django import forms
from django.conf import settings

from django.core.mail import send_mail

class UserCreateForm(UserCreationForm):
    #Add request for access to KID
    kid_request = forms.CharField(max_length=30, min_length=2, required=True)

    class Meta(UserCreationForm.Meta):
        fields = ("username", "email", "phone", "password1", "password2")
        model = ApiUser

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Имя которое будет отображаться на сайте. Не должно содержать пробелов."
        self.fields["email"].label = "Электронная почта. Не обязательно для заполнения, но необходима для восстановления пароля."
        self.fields["kid_request"].label = "Фамилия ребенка к которому будет привязана учетная запись. Обязательна для заполнения."
        self.fields["phone"].label = "Номер телефона. Не обязательно для заполнения."

    # send mail to admin with the last name of the kid wich new user wants to be connected.
    def send_request(self):
        send_mail(
            'Запрос на регистрацию',
            self.cleaned_data["kid_request"] + " от " + self.cleaned_data["username"],
            settings.EMAIL_HOST_USER,
            ['samoilovartem1989@gmail.com'],
            fail_silently=False,
        )

class DateInput(forms.DateInput):
    input_type = 'date'

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = ApiUser
        fields = ['phone', 'email', 'birth_date']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birth_date'].widget = DateInput()




class UserLoginForm(AuthenticationForm):
    model = ApiUser

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Имя которое будет отображаться на сайте"

accounts/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import (LoginView, PasswordResetView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView
from django.db.models.signals import post_save

from . import forms
from . import models


class AccountDetailView(DetailView):
    # model = settings.AUTH_USER_MODEL
    model = models.ApiUser
    template_name = 'accounts/profile.html'


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("home")
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        form.send_request()
        # form.create_profile(self.request)
        return super().form_valid(form)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


# def login_view(login):
# 	template_name = 'accounts/login.html'
# 	authentication_form = forms.UserLoginForm

class UserLoginView(LoginView):
    authentication_form = forms.UserLoginForm
    template_name = "accounts/login.html"


class ProfileUpdateView(UpdateView):
    form_class = forms.UserUpdateForm
    model = models.ApiUser
    template_name = 'accounts/update.html'


class UserPasswordResetView(PasswordResetView):
    success_url = reverse_lazy("home")
    template_name = "accounts/reset_pass.html"
    email_template_name = "accounts/password_reset_email.html"


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "accounts/reset.html"
    success_url = reverse_lazy("accounts:password_reset_complete")


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content_block %}
<div class="container">
    <h1>Авторизация</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Авторизироваться" class="btn btn-success">
    </form>
</div>
<div>
    <a href="{% url 'accounts:reset_pass' %}">Какой же у меня пароь?</a>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content_block %}
<div class="container">
    <h1>Восстановление пароля завершено</h1>
    <p>Ваш пароль был сохранен. Теперь вы можете войти.</p>
    <a href="{% url 'accounts:login' %}">Войти</a>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Вы получили это письмо, потому что вы (или кто-то другой) запросили восстановление пароля от учётной записи на сайте {{ domain }}, которая связана с этим адресом электронной почты.

Пожалуйста, перейдите на эту страницу и введите новый пароль:

{{ protocol}}://{{ domain }}{% url 'accounts:reset' uidb64=uid token=token %}

Ваше имя пользователя (на случай, если вы его забыли): {{ user.username }}

Спасибо, что используете наш сайт!

Команда сайта {{ domain }}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content_block %}
	<h1>{{ user.username }}</h1>
	<p>{{ user.phone }}</p>
	<p>{{ user.last_login }}</p>
	<a href="{% url 'accounts:profile_update' pk=user.pk %}"><p class="btn btn-primary">Изменить профайл</p></a>
{% endblock %}

accounts/templates/accounts/reset.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content_block %}
<div class="container">
    <h1>Введите новый пароль</h1>
    <p>Пожалуйста, введите новый пароль дважды, чтобы мы могли убедиться в правильности написания.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Изменить мой пароль" class="btn btn-success">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_pass.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content_block %}
<div class="container">
    <h1>Восстановление пароля</h1>
    <p>Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Восстановить мой пароль" class="btn btn-success">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content_block %}
<div class="container">
    <h1>Регистрация</h1>
    <h3>Процесс регистрации:</h3>
    <p><strong>Обратите внимание на то, что номер телефона и электронная почта не являются обязательными полями. Фамилия ребенка в форме указывает на ребенка через которого пользователь желает привязаться к группе. Пользователь привязывается к группе только после подтверждения личности регистранта. По этому номер телефона является желательным. Персонал сайта сможет легче с Вами связаться и убедиться, что Вы имеете право на привязку к группе.</strong></p>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Зарегестрироваться" class="btn btn-success">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content_block %}
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="Сохранить" class="btn btn-success">
	</form>
{% endblock %}