DNZ144/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='django_auth'),
    path('groups/', include('group.urls'), name='group'),
    path('registration/', include('accounts.urls'), name='registration'),
    path('accounting/', include('accounting.urls'), name='accounting'),
    path('', views.home_view, name='home'),
    path('contacts/', views.contacts_view, name='contacts'),
    path('info/', views.info_view, name='info'),
    path('info/staff', views.staff_view, name='staff'),
    path('info/schedule', views.schedule_view, name='schedule'),
    path('services/', include('services.urls'), name='services'),
    path('error_500', views.error_500_view, name='error_500'),
]

accounting/urls.py
from django.urls import path, include
from . import views

app_name = 'accounting'

urlpatterns = [
	path('kassas/', views.KassaListView.as_view(), name='kassas_list'),
	path('closed_kassas/', views.KassaClosedListView.as_view(), name='kassas_closed_list'),
	path('charity_kassas/', views.KassaCharityListView.as_view(), name='kassas_charity_list'),
	path('kassas/details/<pk>', views.KassaDetailView.as_view(), name='kassas_details'),
	path('kassas/admin', views.create_operation, name='create_operation'),
	path('kassas/operation_submit', views.operation_submit, name='operation_submit'),
	path('kassas/transfer_submit', views.transfer_submit, name='transfer_submit'),
	path('kassas/withdraw_submit', views.withdraw_submit, name='withdraw_submit'),
	path('kassas/withdraw', views.create_withdraw, name='create_withdraw'),
	path('kassas/transfer', views.create_transfer, name='create_transfer'),
	path('kassas/update_tables', views.refresh_table, name='refresh_table'),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
	path('', views.SignUp.as_view(), name='signup'),
	path('details/<pk>', views.AccountDetailView.as_view(), name='account_detail'),
	path('logout', views.logout_view, name='logout'),
	path('login', views.UserLoginView.as_view(), name='login'),
	path('profile/update/<pk>', views.ProfileUpdateView.as_view(), name='profile_update'),
	path('password_reset', views.UserPasswordResetView.as_view(), name='reset_pass'),
	path('password_reset_confirm/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='reset'),
	path('password/reset/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

group/urls.py
from django.urls import path, include
from . import views

app_name = 'group'

urlpatterns = [
	
]

services/urls.py
from django.urls import path, include
from . import views

app_name = 'services'

urlpatterns = [
	path('', views.MainView.as_view(), name='services_main'),
	path('issues/', views.IssuesView.as_view(), name='issues'),
	path('closed_issues/', views.ClosedIssuesView.as_view(), name='closed_issues'),
	path('issues/details/<pk>', views.DetailIssuesView.as_view(), name='issues_detail'),
	path('issues/create/', views.CreateIssuesView.as_view(), name='issues_create'),
	path('issues/close/<pk>', views.close_issue, name='issues_close'),
	path('issues/create_comment_<pk>/', views.CreateCommentView.as_view(), name='comment_create'),
	path('kid_polls/', include("kids_poll.urls"), name='kids_poll'),
]

services/models.py
from django.db import models
from django.utils import timezone
from group.models import Group
from kids_poll.models import Poll
from django.conf import settings

class IssuesModel(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
	title = models.CharField(max_length=155)
	description = models.TextField(blank=True, null=True)
	is_closed = models.BooleanField(default=False)
	created_date = models.DateTimeField(default=timezone.now)
	closed_date = models.DateTimeField(blank=True, null=True)
	access_to = models.ManyToManyField(Group, related_name='issues')
	img = models.ImageField(upload_to='media', blank=True, null=True)


	def __str__(self):
		return self.title

	def close_issue(self):
		self.closed_date = timezone.now()
		self.is_closed = True
		self.save()

class Comment(models.Model):
    issue = models.ForeignKey(IssuesModel, related_name='issue_comments', on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='author_issue_comments',on_delete=models.CASCADE, null=True)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

class IssuePoll(models.Model):
    issue = models.ForeignKey(IssuesModel, related_name='polls', on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='issue_polls',on_delete=models.CASCADE, null=True, blank=True)
    poll = models.ForeignKey(Poll, related_name='to_issue',on_delete=models.CASCADE, null=True, blank=True)
    created_date = models.DateTimeField(default=timezone.now)

services/forms.py
from django.contrib.auth.models import User
from django import forms
from group.models import Group
from .models import IssuesModel
from accounts.models import ApiUser

class UserForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username', 'password']

class IssuesCreateForm(forms.ModelForm):

	access_to = forms.ModelChoiceField(queryset=Group.objects.all(), empty_label=None)

	class Meta:
		model = IssuesModel
		fields = ['title', 'description', 'img']
		

services/views.py
from django.views.generic import (TemplateView, ListView,
									DetailView, CreateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import IssuesModel, Comment
from group.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

from .forms import IssuesCreateForm

class MainView(TemplateView):
	template_name = 'services/base.html'

class IssuesView(ListView):
	model = IssuesModel
	template_name = 'services/issues.html'

	def get_queryset(self):
		if self.request.user.is_authenticated:
			queryset = IssuesModel.objects.filter(
					access_to__in=self.request.user.get_group_list()
				).filter(is_closed__exact=False)
			return queryset
		else:
			return False

class ClosedIssuesView(ListView):
	model = IssuesModel
	template_name = 'services/closed_issues.html'

	def get_queryset(self):
		if self.request.user.is_authenticated:
			queryset = IssuesModel.objects.filter(
					access_to__kids__parents__exact=User.objects.get(
						id=self.request.user.id
					)
				).filter(is_closed__exact=True)
			return queryset
		else:
			return False

class DetailIssuesView(DetailView):
	model = IssuesModel
	template_name = 'services/issues_detail.html'

class CreateIssuesView(LoginRequiredMixin, CreateView):
	model = IssuesModel
	form_class = IssuesCreateForm
	template_name = 'services/issues_create.html'
	success_url = reverse_lazy('services:issues')

	def form_valid(self, form):
		form.instance.author = self.request.user
		form.instance.save()
		form.instance.access_to.set(self.request.POST.get("access_to"))
		return super().form_valid(form)

class CreateCommentView(LoginRequiredMixin, CreateView):
	model = Comment
	template_name = 'services/issues_create.html'
	fields = ['text']
	success_url = reverse_lazy('services:issues')

	def form_valid(self, form):
		form.instance.author = self.request.user
		form.instance.issue = IssuesModel.objects.get(pk=self.kwargs['pk'])
		form.instance.save()
		return super().form_valid(form)

@login_required
def close_issue(request, pk):
	issue = get_object_or_404(IssuesModel, pk=pk)
	issue.close_issue()
	return redirect('services:issues')

services/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- JQuery -->
	<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<!-- BOOTSTRAP -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Merriweather|PT+Sans&display=swap" rel="stylesheet">
	<!-- MY JAVASCRIPT -->
	<script src="{% static 'js/main.js' %}"></script>
	<!-- MY CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="icon" href="{% static 'train.ico' %}">
	<title>ДНЗ 144</title>
</head>
<body>
	<header>
		{% if user.is_authenticated %}
		<div class="row">
			<div class="col">
				<h3 class="text-left">Вам доступна информация по группе:
			{% if not user.has_group %}
				 <span class="badge badge-secondary">У Вас нет привязки к группе.</span></h3>
				{% else %}
					<span class="badge badge-secondary">
					{% for group in user.get_group_list %}{{ group }}{% endfor %}
					</span>
				</h3>
			{% endif %}

			</div>
			{% if user.is_superuser %}
			<div class="col-md-auto">
				<a href="{% url 'accounting:create_operation' %}" class="btn btn-success">В админку</a>
			</div>
			{% endif %}
			<div class="col-md-auto">
				<a class="btn btn-primary" href="{% url 'accounts:account_detail' pk=user.pk %}">Вы зашли как {{ user.get_username }}</a>
			</div>
			<div class="col col-lg-2">
				<a class="btn btn-warning justify-content-end" href="{% url 'accounts:logout' %}">Выйти из учетной записи</a>
		    </div>
		</div>
		{% else %}
		<a href="{% url 'accounts:login' %}">
			<button type="button" class="btn btn-primary btn-lg btn-block">Войдите в учетную запись</button>
		</a>
		<a href="{% url 'accounts:signup' %}">
			<button type="button" class="btn btn-warning btn-lg btn-block">Или подайте заявку на регистрацию</button>
		</a>
		{% endif %}	
		<a href="{% url 'home' %}"><h1 class="text-decoration-none text-center" id="main-title">ДНЗ 144</h1></a>
		<div>
			<nav>
				<ul class="nav nav-tabs justify-content-center">
					<a class="nav-link" href="{% url 'home' %}"><li class="nav-item">Главная</li></a>
					<a class="nav-link" href="{% url 'services:services_main' %}"><li class="nav-item">Сервисы</li></a>
					<a class="nav-link" href="{% url 'info' %}"><li class="nav-item">Информация</li></a>
					{% if user.is_authenticated %}
					<a class="nav-link" href="{% url 'accounting:kassas_list' %}"><li class="nav-item">Бухгалтерия</li></a>
					{% endif %}
					<a class="nav-link" href="{% url 'contacts' %}"><li class="nav-item">Контакты</li></a>
				</ul>
			</nav>
		</div>	
	</header>
	<div class="container">
	{% block content_block %}{% endblock %}		
	</div>
	{% block js_block %}{% endblock %}
</body>
</html>

services/templates/contacts.html
{% extends 'base.html' %}

{% block content_block %}
	<div class="container">
		<br>
		<div class="row">
			<div class="col-8" style="width:50%; height:600px">
				<iframe width='100%' height='100%' id='mapcanvas' src='https://maps.google.com/maps?q=50.525970, 30.511518&output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'><div class='zxos8_gm'><a href='https://sites.google.com/site/xenoncharles/xperia-1-deals'>SONY</a></div><div style='overflow:hidden;'><div id='gmap_canvas' style='height:100%;width:700px;'></div><div><small>Powered by <a href='https://www.embedgooglemap.co.uk'>Embed Google Map</a></small></div></iframe>
			</div>
			<div class="col-4">
				<h2>Контакты:</h2>
				<ul>
					<li>Полное наименование: ДОШКІЛЬНИЙ НАВЧАЛЬНИЙ ЗАКЛАД №144</li>
					<li>Код ЕДРПОУ / лицензия: 22877100</li>
					<li>адрес: вул. Північна 42, Київ</li>
					<li>район: Оболонский</li>
					<li>телефон: 411-44-32</li>
				</ul>
			</div>
		</div>
	</div>
	

{% endblock %}

services/templates/home.html
{% extends 'base.html' %}

{% block content_block %}
<div class="container">
	<div class="jumbotron">
		<h2>Добро пожаловать на неофициальный сайт ДНЗ 144</h2>
		<p>{{ text|linebreaks }}</p>		
	</div>	
</div>
{% endblock %}

services/templates/info.html
{% extends 'base.html' %}

{% block content_block %}
<nav>
	<ul class="nav nav-pills nav-fill">
		<a class="nav-item nav-link" href="{% url 'schedule' %}">Рассписание</a>
		<a class="nav-item nav-link" href="{% url 'staff' %}">Персонал</a>
	</ul>
</nav>
{% if user.is_authenticated %}
	{% block info_block %}{% endblock %}
{% else %}
		<p>Возможно, вы забыли <a href="{% url 'accounts:login' %}">зайти в учетную запись</a>.</p>
{% endif %}
{% endblock %}