DNZ144/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='django_auth'),
    path('groups/', include('group.urls'), name='group'),
    path('registration/', include('accounts.urls'), name='registration'),
    path('accounting/', include('accounting.urls'), name='accounting'),
    path('', views.home_view, name='home'),
    path('contacts/', views.contacts_view, name='contacts'),
    path('info/', views.info_view, name='info'),
    path('info/staff', views.staff_view, name='staff'),
    path('info/schedule', views.schedule_view, name='schedule'),
    path('services/', include('services.urls'), name='services'),
    path('error_500', views.error_500_view, name='error_500'),
]

accounting/urls.py
from django.urls import path, include
from . import views

app_name = 'accounting'

urlpatterns = [
	path('kassas/', views.KassaListView.as_view(), name='kassas_list'),
	path('closed_kassas/', views.KassaClosedListView.as_view(), name='kassas_closed_list'),
	path('charity_kassas/', views.KassaCharityListView.as_view(), name='kassas_charity_list'),
	path('kassas/details/<pk>', views.KassaDetailView.as_view(), name='kassas_details'),
	path('kassas/admin', views.create_operation, name='create_operation'),
	path('kassas/operation_submit', views.operation_submit, name='operation_submit'),
	path('kassas/transfer_submit', views.transfer_submit, name='transfer_submit'),
	path('kassas/withdraw_submit', views.withdraw_submit, name='withdraw_submit'),
	path('kassas/withdraw', views.create_withdraw, name='create_withdraw'),
	path('kassas/transfer', views.create_transfer, name='create_transfer'),
	path('kassas/update_tables', views.refresh_table, name='refresh_table'),
]

group/urls.py
from django.urls import path, include
from . import views

app_name = 'group'

urlpatterns = [
	
]

accounting/models.py
from django.db import models
from django.db.models import Sum

from accounts.models import ApiUser
from group.models import Group, Kid


class Kassa(models.Model):
    name = models.CharField(max_length=32)
    card = models.CharField(max_length=16, null=True, blank=True)
    group = models.ForeignKey(Group, related_name='kassas',
                              on_delete=models.CASCADE, null=True)
    create_date = models.DateField(auto_now_add=True, null=True)
    descripton = models.TextField(null=True, blank=True)
    is_charity = models.BooleanField(null=True, default=False)
    is_active = models.BooleanField(null=True, default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "details/%i" % self.id

    def get_cre_sum(self):
        return self.operations.filter(trans_type="CRE").aggregate(Sum('amount'))['amount__sum']

    def get_deb_sum(self):
        return self.operations.filter(trans_type="DEB").aggregate(Sum('amount'))['amount__sum']

    def get_saldo(self):
        cre = self.operations.filter(trans_type="CRE").aggregate(Sum('amount'))['amount__sum']
        deb = self.operations.filter(trans_type="DEB").aggregate(Sum('amount'))['amount__sum']
        return self._get_saldo(deb, cre)

    def get_saldo_from(self, date_from):
        cre = self.operations.filter(trans_type="CRE", create_date__gte=date_from).aggregate(Sum('amount'))['amount__sum']
        deb = self.operations.filter(trans_type="DEB", create_date__gte=date_from).aggregate(Sum('amount'))['amount__sum']
        return self._get_saldo(deb, cre)

    @staticmethod
    def _get_saldo(deb, cre):
        if deb and cre:
            return deb - cre
        elif deb:
            return deb
        else:
            return 0

    def kids_paid(self):
        kids_paid = [kid[0] for kid in self.operations.filter(trans_type="DEB").values_list('kid')]
        return kids_paid

    def kid_balance(self, kid, at=None):
        if at:
            query = {'kassa__is_charity': False, 'kid': kid, 'create_date__gt': at}
        else:
            query = {'kassa__is_charity': False, 'kid': kid}
        cre = self.operations.filter(**query, trans_type="CRE").aggregate(Sum('amount'))['amount__sum']
        deb = self.operations.filter(**query, trans_type="DEB").aggregate(Sum('amount'))['amount__sum']
        if deb and cre:
            return {'cre': cre, 'deb': deb, 'balance': deb - cre}
        elif deb:
            return {'cre': 0, 'deb': deb, 'balance': deb}
        elif cre:
            return {'cre': cre, 'deb': 0, 'balance': 0 - cre}
        else:
            return {'cre': 0, 'deb': 0, 'balance': 0}

    def transfer_to_account(self, amount: float, kid: Kid):
        kid.kid_balance.charge_balance(amount)
        Operation.objects.create(
            amount=amount,
            kassa=self,
            kid=kid,
            trans_type='DEB',
        )

    def transfer_from_account(self, amount: float, kid: Kid):
        kid.kid_balance.withdraw_balance(amount)
        Operation.objects.create(
            amount=amount,
            kassa=self,
            kid=kid,
            trans_type='CRE',
        )


class Operation(models.Model):
    TRANS_TYPES = {
        ('DEB', "Приход"),
        ('CRE', "Расход"),
    }

    kassa = models.ForeignKey(Kassa, related_name='operations',
                              on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)
    kid = models.ForeignKey(Kid, related_name='operations',
                            on_delete=models.CASCADE,
                            null=True, blank=True)
    user = models.ForeignKey(ApiUser, on_delete=models.CASCADE, null=True)
    trans_type = models.CharField(max_length=3, choices=TRANS_TYPES, null=True)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    img = models.ImageField(upload_to='media', blank=True)
    comment = models.CharField(max_length=155, null=True, blank=True)
    update_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return "{} {}".format(self.create_date.date(), str(self.kid))

accounting/forms.py
from django import forms
from .models import Operation, Kassa

class CreateOperationForm(forms.ModelForm):

	class Meta:
		model = Operation
		fields = ['trans_type', 'kassa', 'kid', 'amount', 'comment']

class CreateTransferForm(forms.Form):
	from_kassa = forms.ModelChoiceField(queryset=Kassa.objects.all(), empty_label=None)
	to_kassa = forms.ModelChoiceField(queryset=Kassa.objects.all(), empty_label=None)
	amount = forms.DecimalField(max_digits=7, decimal_places=2, required=False)

class CreateWithdrawForm(forms.Form):
	from_kassa = forms.ModelChoiceField(queryset=Kassa.objects.all(), empty_label=None)
	amount = forms.DecimalField(max_digits=7, decimal_places=2)
	comment = forms.CharField(max_length=120, required=False)



		

accounting/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from django.http import JsonResponse

from .models import Kassa, Operation
from group.models import Group
from accounts.models import ApiUser
from django.db.models import Sum

# forms
from .forms import CreateOperationForm, CreateWithdrawForm, CreateTransferForm

# functions for kassa's operations
from .utils import *


@login_required
def test_view(request):
    kassa = Kassa.objects.all()[1]
    return render(request, 'accounting/accounting_base.html', context={'kassa': kassa})


from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class KassaListView(LoginRequiredMixin, ListView):
    model = Kassa
    # get_context_object_name = 'kassas'
    template_name = 'kassas_list.html'
    redirect_field_name = 'accounts:login'

    def get_queryset(self):
        if not self.request.user.has_group():
            return None
        # TODO: create list of groups.
        queryset = (Group.objects.
                    get(pk=self.request.user.get_group_list()[0].pk).
                    kassas.filter(is_active=True, is_charity=False).
                    order_by('-create_date'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_sum = sum([kassa.get_saldo() for kassa in Group.objects.get(pk=self.request.user.get_group_list()[
            0].pk).kassas.all()]) if self.request.user.get_group_list() else "Нет доступа к группам"
        context['total_sum'] = total_sum
        return context


class KassaClosedListView(LoginRequiredMixin, ListView):
    model = Kassa
    # get_context_object_name = 'kassas'
    template_name = 'kassas_closed_list.html'
    redirect_field_name = 'accounts:login'

    def get_queryset(self):
        if not self.request.user.has_group():
            return None
        # TODO: create list of groups.
        queryset = (Group.objects.
                    get(pk=self.request.user.get_group_list()[0].pk).
                    kassas.filter(is_active=False).
                    order_by('-create_date'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_sum = sum([kassa.get_saldo() for kassa in Group.objects.get(pk=self.request.user.get_group_list()[
            0].pk).kassas.all()]) if self.request.user.get_group_list() else "Нет доступа к группам"
        context['total_sum'] = total_sum
        return context


class KassaCharityListView(LoginRequiredMixin, ListView):
    model = Kassa
    template_name = 'kassas_charity_list.html'
    redirect_field_name = 'accounts:login'

    def get_queryset(self):
        if not self.request.user.has_group():
            return None
        # TODO: create list of groups.
        queryset = (Group.objects.
                    get(pk=self.request.user.get_group_list()[0].pk).
                    kassas.filter(is_active=True, is_charity=True).
                    order_by('-create_date'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_sum = sum([kassa.get_saldo() for kassa in Group.objects.get(pk=self.request.user.get_group_list()[
            0].pk).kassas.all()]) if self.request.user.get_group_list() else "Нет доступа к группам"
        context['total_sum'] = total_sum
        return context


class KassaDetailView(LoginRequiredMixin, DetailView):
    model = Kassa
    template_name = 'kassas_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kid_balance'] = context['kassa'].kid_balance(self.request.user.kids.first())['balance']
        return context


# Create Operation
@login_required
def create_operation(request):
    form = CreateOperationForm
    return render(request, 'create_operation.html', context={'form': form})


@login_required
def create_withdraw(request):
    form = CreateWithdrawForm
    return render(request, 'create_withdraw.html', context={'form': form})


@login_required
def create_transfer(request):
    form = CreateTransferForm
    return render(request, 'create_transfer.html', context={'form': form})


@login_required
def refresh_table(request):
    import create_google_sheet_kassas as refresh
    refresh.main()
    return JsonResponse(data={'success': True})


@require_http_methods(["POST"])
def withdraw_submit(request):
    response_data = {}
    form = CreateWithdrawForm(request.POST)
    if form.is_valid():
        form = form.cleaned_data
        kassa = form['from_kassa']
        withdraw(kassa, form['amount'],
                 user=ApiUser.objects.get(id=request.user.id),
                 comment=form.get('comment', None))
        # kassa.withdraw(form['amount'], ApiUser.objects.get(id=request.user.id))
        return JsonResponse(response_data)


@require_http_methods(["POST"])
def transfer_submit(request):
    """
	if not amount provide:
	function transfer all kassa's balance to another kassa. End part amount for each Kid dependent from their donate.
		If balance is negative, function draws amount from another kassa equly from each kid. Anyway, from_k's balance
		will set to zero.
	else: transfer provided amount.
	:param request: POST from FORM.
    :return: empty dictionary object.
	"""
    response_data = {}
    if request.is_ajax:
        responsible_user = ApiUser.objects.get(id=request.user.id)
        form = CreateTransferForm(request.POST)
        if form.is_valid():
            form = form.cleaned_data
            from_k = form['from_kassa']
            to_k = form['to_kassa']
            amount = form['amount']
            if from_k and to_k:
                trans_func(from_k, to_k, responsible_user, amount)
            return JsonResponse(response_data)
        else:
            return JsonResponse(response_data)


@require_http_methods(["POST"])
def operation_submit(request):
    response_data = {}
    if request.is_ajax:
        if request.method == 'POST':
            data = request.POST
            Operation.objects.create(
                kassa=Kassa.objects.get(pk=data['kassa']),
                kid=Kid.objects.get(pk=data['kid']),
                amount=data['amount'],
                user=ApiUser.objects.get(id=request.user.id),
                trans_type=data['trans_type'],
                comment=data['comment']
            )
            return JsonResponse(response_data)

accounting/templates/create_operation.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content_block %}
{% if user.is_superuser %}
	<h1>Движение денежных средств</h1>
	<form method="POST" id="operation-form">
		{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-warning" type="submit" name="submit">
	</form>

	<a href="{% url 'accounting:create_withdraw' %}"><button class="btn btn-danger">Списать средства</button></a>
	<a href="{% url 'accounting:create_transfer' %}"><button class="btn btn-warning">Перекинуть балансы</button></a>
	<button id="update_table" class="btn btn-warning">Обновить таблицу</button>
{% endif %}
{% endblock %}

<!-- JS -->
{% block js_block %}
<script type="text/javascript">
	$('#operation-form').submit(function(){
	    $.ajax({
	        type: "POST",
	        url: "{% url 'accounting:operation_submit' %}",
	        dataType: "json",
	        async: true,
	        data: $(this).serialize(),
	        success: function(response) {
	            alert('Операция создана!');

	        },
	        error:  function(response) {
	        	alert("Операция не удалась!")
	        }
	    });
	    return false;
	});
	$('#update_table').click(function(){
			$.ajax({
					type: "GET",
					url: "{% url 'accounting:refresh_table' %}",
					// dataType: "json",
					async: true,
					// data: $(this).serialize(),
					success: function(response) {
							alert('Процесс запущен.');
					},
					error:  function(response) {
						alert("Операция не удалась!")
					}
			});
			return false;
	});
</script>
{% endblock %}

accounting/templates/create_transfer.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content_block %}
{% if user.is_superuser %}
	<h1>Transfer</h1>
	<form method="POST" id="transfer-form">
		{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-warning" type="submit" name="Transfer">	
	</form>
{% endif %}
{% endblock %}

<!-- JS -->
{% block js_block %}
<script type="text/javascript">
	$('#transfer-form').submit(function(){
	    $.ajax({
	        type: "POST",
	        url: "{% url 'accounting:transfer_submit' %}",
	        dataType: "json",
	        async: true,
	        data: $(this).serialize(),
	        success: function(response) {
	            alert('Средства сняты со счетов!');

	        },
	        error:  function(response) {
	        	alert("Операция не удалась!")
	        }                 
	    });
	    return false;
	});
</script>
{% endblock %}

accounting/templates/create_withdraw.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content_block %}
{% if user.is_superuser %}
	<h1>Withdraw</h1>
	<form method="POST" id="withdraw-form">
		{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-warning" type="submit" name="GO">	
	</form>
{% endif %}
{% endblock %}

<!-- JS -->
{% block js_block %}
<script type="text/javascript">
	$('#withdraw-form').submit(function(){
	    $.ajax({
	        type: "POST",
	        url: "{% url 'accounting:withdraw_submit' %}",
	        dataType: "json",
	        async: true,
	        data: $(this).serialize(),
	        success: function(response) {
	            alert('Операция создана!');

	        },
	        error:  function(response) {
	        	alert("Операция не удалась!")
	        }                 
	    });
	    return false;
	});
</script>
{% endblock %}

accounting/templates/kassas_base.html
{% extends 'base.html' %}

{% block content_block %}
<nav>
	<ul class="nav nav-pills nav-fill">
		<a class="nav-item nav-link" href="{% url 'accounting:kassas_list' %}">Открытые фонды</a>
		<a class="nav-item nav-link" href="{% url 'accounting:kassas_closed_list' %}">Закрытые фонды</a>
		<a class="nav-item nav-link" href="{% url 'accounting:kassas_charity_list' %}">Благотворительность</a>
	</ul>
</nav>
<div class="container">
	<h4>Общий баланс группы: {{ total_sum|floatformat }}.</h4>
	<p>Ваш общий баланс: {{ user.get_balanse|floatformat:2 }}</p>
	{% block kassas_block %}{% endblock %}
</div>
{% endblock %}

accounting/templates/kassas_charity_list.html
{% extends 'kassas_base.html' %}

{% block kassas_block %}
	<h1>Благотворительность</h1>
	<br/>
	{% for kassa in kassa_list %}
	<div class="card mb-3">
		<div class="card-body">
			<h5 class="card-title">
				<a href="{% url 'accounting:kassas_details' pk=kassa.pk %}">Фонд: {{ kassa.name }}</a>
			</h5>
			<p class="card-text">{{ kassa.descripton }}</p>
			<p class="card-text">Остаток: {{ kassa.get_saldo|floatformat:2 }}</p>
		</div>
	</div>
	{% endfor %}
{% endblock %}

accounting/templates/kassas_closed_list.html
{% extends 'kassas_base.html' %}

{% block kassas_block %}
	<h1>Закрытые фонды</h1>
	<br/>
	{% for kassa in kassa_list %}
	<div class="card mb-3">
		<div class="card-body">
			<h5 class="card-title">
				<a href="{% url 'accounting:kassas_details' pk=kassa.pk %}">Фонд: {{ kassa.name }}</a>
			</h5>
			<p class="card-text">{{ kassa.descripton }}</p>
			<p class="card-text">Остаток: {{ kassa.get_saldo|floatformat:2 }}</p>	
		</div>
	</div>
	{% endfor %}
{% endblock %}

accounting/templates/kassas_details.html
{% extends 'kassas_base.html' %}

{% block kassas_block %}
	{% block accounting_block %}
		<h3>Фонд: {{ kassa.name }}</h3>
		<table class="table table-striped">
			<tbody>
				<tr>
					<th scope="row">Карта для пополнения фонда:</th>
					<td class="text-right">{{ kassa.card }}</td>
				</tr>
				<tr>
					<th scope="row">Общие доходы:</th>
					<td class="text-right">{{ kassa.get_deb_sum|floatformat:2 }}</td>
				</tr>
				<tr>
					<th scope="row">Общие расходы:</th>
					<td class="text-right">{{ kassa.get_cre_sum|floatformat:2 }}</td>
				</tr>
				<tr>
					<th scope="row">Остаток:</th>
					<td class="text-right">{{ kassa.get_saldo|floatformat:2 }}</td>
				</tr>
				<tr>
					<th scope="row">Оплатило:</th>
					<td class="text-right">{{ kassa.kids_paid|length }}/{{ kassa.group.kids.all.count }}</td>
				</tr>
				<tr>
					<th scope="row">Последние данные были внесены:</th>
					<td class="text-right">{{ kassa.operations.last.create_date|date:"d M Y" }}</td>
				</tr>
				{% if user.kids.first.id in kassa.kids_paid %}
				<tr>
					<th scope="row">Оплата от {{ user.kids.first.last_name }}</th>
					<td class="text-right">Есть</td>
				</tr>
				{% else %}
				<tr>
					<th scope="row">Оплата от {{ user.kids.first.last_name }}</th>
					<td class="text-right">Нет</td>
				</tr>
				{% endif %}
				<tr>
					<th scope="row">Ваш баланс:</th>
					<td class="text-right">{{ kid_balance|floatformat:2 }}</td>
				</tr>
			</tbody>
		</table>
	{% endblock %}
{% endblock %}

accounting/templates/kassas_list.html
{% extends 'base.html' %}

{% block content_block %}
	<h1>Бухгалтерия</h1>
	<h4>Общий баланс группы: {{ total_sum|floatformat }}.</h4>
	<p>Ваш общий баланс: {{ user.get_balanse|floatformat:2 }}</p>
	{% for kassa in kassa_list %}
	<div class="card mb-3">
		<div class="card-body">
			<h5 class="card-title">
				<a href="{{ kassa.get_absolute_url }}">Фонд: {{ kassa.name }}</a>
			</h5>
			<p class="card-text">{{ kassa.descripton }}</p>
			<p class="card-text">Остаток: {{ kassa.get_saldo|floatformat:2 }}</p>	
		</div>
	</div>
	{% endfor %}
{% endblock %}