DNZ144/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='django_auth'),
    path('groups/', include('group.urls'), name='group'),
    path('registration/', include('accounts.urls'), name='registration'),
    path('accounting/', include('accounting.urls'), name='accounting'),
    path('', views.home_view, name='home'),
    path('contacts/', views.contacts_view, name='contacts'),
    path('info/', views.info_view, name='info'),
    path('info/staff', views.staff_view, name='staff'),
    path('info/schedule', views.schedule_view, name='schedule'),
    path('services/', include('services.urls'), name='services'),
    path('error_500', views.error_500_view, name='error_500'),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
	path('', views.SignUp.as_view(), name='signup'),
	path('details/<pk>', views.AccountDetailView.as_view(), name='account_detail'),
	path('logout', views.logout_view, name='logout'),
	path('login', views.UserLoginView.as_view(), name='login'),
	path('profile/update/<pk>', views.ProfileUpdateView.as_view(), name='profile_update'),
	path('password_reset', views.UserPasswordResetView.as_view(), name='reset_pass'),
	path('password_reset_confirm/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='reset'),
	path('password/reset/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

group/urls.py
from django.urls import path, include
from . import views

app_name = 'group'

urlpatterns = [
	
]

kids_poll/urls.py
from django.urls import path
from . import views

app_name = 'kids_poll'

urlpatterns = [
	path('votes/<poll_id>', views.vote, name='vote'),
	path('polls/<poll_id>', views.poll_view, name='poll_view'),
	path('result/<poll_id>', views.result, name='result'),
	path('polls/', views.PollsViewList.as_view(), name='polls_list'),
	path('polls/create/', views.CreatePollView.as_view(), name='polls_create'),
]

services/urls.py
from django.urls import path, include
from . import views

app_name = 'services'

urlpatterns = [
	path('', views.MainView.as_view(), name='services_main'),
	path('issues/', views.IssuesView.as_view(), name='issues'),
	path('closed_issues/', views.ClosedIssuesView.as_view(), name='closed_issues'),
	path('issues/details/<pk>', views.DetailIssuesView.as_view(), name='issues_detail'),
	path('issues/create/', views.CreateIssuesView.as_view(), name='issues_create'),
	path('issues/close/<pk>', views.close_issue, name='issues_close'),
	path('issues/create_comment_<pk>/', views.CreateCommentView.as_view(), name='comment_create'),
	path('kid_polls/', include("kids_poll.urls"), name='kids_poll'),
]

services/models.py
from django.db import models
from django.utils import timezone
from group.models import Group
from kids_poll.models import Poll
from django.conf import settings

class IssuesModel(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
	title = models.CharField(max_length=155)
	description = models.TextField(blank=True, null=True)
	is_closed = models.BooleanField(default=False)
	created_date = models.DateTimeField(default=timezone.now)
	closed_date = models.DateTimeField(blank=True, null=True)
	access_to = models.ManyToManyField(Group, related_name='issues')
	img = models.ImageField(upload_to='media', blank=True, null=True)


	def __str__(self):
		return self.title

	def close_issue(self):
		self.closed_date = timezone.now()
		self.is_closed = True
		self.save()

class Comment(models.Model):
    issue = models.ForeignKey(IssuesModel, related_name='issue_comments', on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='author_issue_comments',on_delete=models.CASCADE, null=True)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

class IssuePoll(models.Model):
    issue = models.ForeignKey(IssuesModel, related_name='polls', on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='issue_polls',on_delete=models.CASCADE, null=True, blank=True)
    poll = models.ForeignKey(Poll, related_name='to_issue',on_delete=models.CASCADE, null=True, blank=True)
    created_date = models.DateTimeField(default=timezone.now)

services/forms.py
from django.contrib.auth.models import User
from django import forms
from group.models import Group
from .models import IssuesModel
from accounts.models import ApiUser

class UserForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username', 'password']

class IssuesCreateForm(forms.ModelForm):

	access_to = forms.ModelChoiceField(queryset=Group.objects.all(), empty_label=None)

	class Meta:
		model = IssuesModel
		fields = ['title', 'description', 'img']
		

services/views.py
from django.views.generic import (TemplateView, ListView,
									DetailView, CreateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import IssuesModel, Comment
from group.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

from .forms import IssuesCreateForm

class MainView(TemplateView):
	template_name = 'services/base.html'

class IssuesView(ListView):
	model = IssuesModel
	template_name = 'services/issues.html'

	def get_queryset(self):
		if self.request.user.is_authenticated:
			queryset = IssuesModel.objects.filter(
					access_to__in=self.request.user.get_group_list()
				).filter(is_closed__exact=False)
			return queryset
		else:
			return False

class ClosedIssuesView(ListView):
	model = IssuesModel
	template_name = 'services/closed_issues.html'

	def get_queryset(self):
		if self.request.user.is_authenticated:
			queryset = IssuesModel.objects.filter(
					access_to__kids__parents__exact=User.objects.get(
						id=self.request.user.id
					)
				).filter(is_closed__exact=True)
			return queryset
		else:
			return False

class DetailIssuesView(DetailView):
	model = IssuesModel
	template_name = 'services/issues_detail.html'

class CreateIssuesView(LoginRequiredMixin, CreateView):
	model = IssuesModel
	form_class = IssuesCreateForm
	template_name = 'services/issues_create.html'
	success_url = reverse_lazy('services:issues')

	def form_valid(self, form):
		form.instance.author = self.request.user
		form.instance.save()
		form.instance.access_to.set(self.request.POST.get("access_to"))
		return super().form_valid(form)

class CreateCommentView(LoginRequiredMixin, CreateView):
	model = Comment
	template_name = 'services/issues_create.html'
	fields = ['text']
	success_url = reverse_lazy('services:issues')

	def form_valid(self, form):
		form.instance.author = self.request.user
		form.instance.issue = IssuesModel.objects.get(pk=self.kwargs['pk'])
		form.instance.save()
		return super().form_valid(form)

@login_required
def close_issue(request, pk):
	issue = get_object_or_404(IssuesModel, pk=pk)
	issue.close_issue()
	return redirect('services:issues')

services/templates/services/base.html
{% extends 'base.html' %}

{% block content_block %}
<nav>
	<ul class="nav nav-pills nav-fill">
		<a class="nav-item nav-link" href="{% url 'services:issues' %}">Открытые вопросы</a>
		<a class="nav-item nav-link" href="{% url 'services:closed_issues' %}">Закрытые вопросы</a>
		<a class="nav-item nav-link" href="{% url 'services:kids_poll:polls_list' %}">Голосования</a>
	</ul>
</nav>
<div class="container">
	{% block spec_block %}{% endblock %}
</div>
{% endblock %}

services/templates/services/closed_issues.html
{% extends 'services/base.html' %}
{% load static %}

{% block spec_block %}
<h2>Закрытые вопросы</h2>
<div>
	{% if issuesmodel_list %}
	{% for issue in issuesmodel_list %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">{{ issue.title }}</h5>
    <p class="card-text">{{ issue.description }}</p>
    <p class="card-text"><small class="text-muted">Тема закрыта: {{ issue.closed_date }}</small></p>
  </div>
</div>
	{% endfor %}
	{% else %}
		<p>Зактырых вопросов доступных вашей учетной записи не найдено.</p>
		<p>Возможно, вы забыли <a href="{% url 'accounts:login' %}">зайти в учетную запись</a>.</p>
	{% endif %}
</div>



{% endblock %}

services/templates/services/issues.html
{% extends 'services/base.html' %}
{% load static %}

{% block spec_block %}
<h2>Открытые вопросы</h2>
{% if user.has_groups or user.is_superuser %}
<a href="{% url 'services:issues_create' %}"><p class="btn btn-primary">Открыть новый вопрос</p></a>
{% endif %}
<div>
	{% if issuesmodel_list %}
	{% for issue in issuesmodel_list %}
<div class="card mb-3">
  <div class="card-body">
  	{% if issue.img %}
  	<img src="{% static issue.img.url %}" class="card-img-top" alt="">
  	{% endif %}
    <h5 class="card-title"><a href="{% url 'services:issues_detail' pk=issue.pk %}">{{ issue.title|upper }}</a></h5>
    <p class="card-text">{{ issue.description|truncatechars:300 }}</p>
    <p class="card-text">Пост создал: {{ issue.author }}</p>
    <p class="card-text"><small class="text-muted">{{ issue.created_date }}</small></p>
    {% if user.is_superuser %}
    <a class="btn btn-danger" href="{% url 'services:issues_close' pk=issue.pk %}">Закрыть вопрос</a>
    {% endif %}
  </div>
</div>
	{% endfor %}
	{% else %}
		<p>Открытых вопросов доступных вашей учетной записи не найдено.</p>
		<p>Возможно, вы забыли <a href="{% url 'accounts:login' %}">зайти в учетную запись</a>.</p>
	{% endif %}
</div>



{% endblock %}

services/templates/services/issues_create.html
{% extends 'services/base.html' %}
{% load crispy_forms_tags %}

{% block spec_block %}
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="Создать" class="btn btn-success">
	</form>
{% endblock %}

services/templates/services/issues_detail.html
{% extends 'services/base.html' %}
{% load static %}

{% block spec_block %}
	<div class="issue border border-info">
	<h4>{{ issuesmodel.title }}</h4>
	<p>{{ issuesmodel.description|linebreaksbr }}</p>
	<a href="{% url 'services:comment_create' pk=issuesmodel.pk %}"><p class="btn btn-primary">Комментировать</p></a>
	<div>
		<p>{{ issuesmodel.polls.first.poll }}</p>
	</div>		
	</div>
	<div class="comments">		
		{% if issuesmodel.issue_comments %}
			{% for comment in issuesmodel.issue_comments.all %}
			<div class="border border-info rounded-top">
				<p>{{ comment.author }}</p>
				<p>{{ comment.text }}</p>
				<p>{{ comment.created_date }}</p>				
			</div>
			{% endfor %}
		{% endif %}
	</div>
{% endblock %}

services/templates/services/polls_list.html
{% extends 'services/base.html' %}


{% block spec_block %}
<h2>Опросы</h2>
<div>
{% if user.is_authenticated %}
	<a href="{% url 'services:polls_create' %}"><p class="btn btn-primary">Создать новый опрос</p></a>
{% endif %}
	{% if poll_list %}
	{% for poll in poll_list %}
		<a href="{% url 'services:poll:poll_view' poll_id=poll.id %}"><p>{{ poll.question }}</p></a>
	{% endfor %}
	{% else %}
		<p>Опросов доступных вашей учетной записи не найдено.</p>
		<p>Возможно, вы забыли <a href="{% url 'login' %}">зайти в учетную запись</a>.</p>
	{% endif %}
</div>

{% endblock %}